// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.Answer")
@ServiceName("medizin.server.domain.Answer")
public interface AnswerRequest extends RequestContext {

    abstract Request<java.lang.Long> countAnswers();

    abstract Request<java.util.List<medizin.client.managed.request.AnswerProxy>> findAllAnswers();

    abstract Request<medizin.client.managed.request.AnswerProxy> findAnswer(Long id);

    abstract Request<java.util.List<medizin.client.managed.request.AnswerProxy>> findAnswerEntries(int firstResult, int maxResults);

    abstract InstanceRequest<medizin.client.managed.request.AnswerProxy, java.lang.Void> persist();

    abstract InstanceRequest<medizin.client.managed.request.AnswerProxy, java.lang.Void> remove();

    abstract InstanceRequest<medizin.client.managed.request.AnswerProxy, java.lang.Void> countRedactionalBases();

    abstract InstanceRequest<medizin.client.managed.request.AnswerProxy, java.lang.Void> findAllRedactionalBases();

    abstract InstanceRequest<medizin.client.managed.request.AnswerProxy, java.lang.Void> findRedactionalBase(Long id);

    abstract InstanceRequest<medizin.client.managed.request.AnswerProxy, java.lang.Void> findRedactionalBaseEntries(int firstResult, int maxResults);
}
