// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.Date;
import java.util.Set;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.AssesmentQuestion")
@ProxyForName("medizin.server.domain.AssesmentQuestion")
public interface AssesmentQuestionProxy extends EntityProxy {

    abstract Date getDateAdded();

    abstract void setDateAdded(Date dateAdded);

    abstract Date getDateChanged();

    abstract void setDateChanged(Date dateChanged);

    abstract PersonProxy getRewiewer();

    abstract void setRewiewer(PersonProxy rewiewer);

    abstract PersonProxy getAutor();

    abstract void setAutor(PersonProxy autor);

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);

    abstract Integer getOrderAversion();

    abstract void setOrderAversion(Integer orderAversion);

    abstract Integer getOrderBversion();

    abstract void setOrderBversion(Integer orderBversion);

    abstract Double getTrenschaerfe();

    abstract void setTrenschaerfe(Double trenschaerfe);

    abstract Double getSchwierigkeit();

    abstract void setSchwierigkeit(Double schwierigkeit);

    abstract Boolean getIsAssQuestionAcceptedRewiever();

    abstract void setIsAssQuestionAcceptedRewiever(Boolean isAssQuestionAcceptedRewiever);

    abstract Boolean getIsAssQuestionAcceptedAdmin();

    abstract void setIsAssQuestionAcceptedAdmin(Boolean isAssQuestionAcceptedAdmin);

    abstract Boolean getIsAssQuestionAdminProposal();

    abstract void setIsAssQuestionAdminProposal(Boolean isAssQuestionAdminProposal);

    abstract Boolean getIsAssQuestionAcceptedAutor();

    abstract void setIsAssQuestionAcceptedAutor(Boolean isAssQuestionAcceptedAutor);

    abstract QuestionProxy getQuestion();

    abstract void setQuestion(QuestionProxy question);

    abstract AssesmentProxy getAssesment();

    abstract void setAssesment(AssesmentProxy assesment);

    abstract Set<medizin.client.managed.request.AnswerToAssQuestionProxy> getAnswersToAssQuestion();

    abstract void setAnswersToAssQuestion(Set<AnswerToAssQuestionProxy> answersToAssQuestion);
}
