// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.Assesment")
@ServiceName("medizin.server.domain.Assesment")
public interface AssesmentRequest extends RequestContext {

    abstract InstanceRequest<medizin.client.managed.request.AssesmentProxy, java.lang.Void> persist();

    abstract InstanceRequest<medizin.client.managed.request.AssesmentProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countAssesments();

    abstract Request<java.util.List<medizin.client.managed.request.AssesmentProxy>> findAllAssesments();

    abstract Request<medizin.client.managed.request.AssesmentProxy> findAssesment(Long id);

    abstract Request<java.util.List<medizin.client.managed.request.AssesmentProxy>> findAssesmentEntries(int firstResult, int maxResults);
}
