// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import medizin.client.shared.AccessRights;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.EventAccess")
@ProxyForName("medizin.server.domain.EventAccess")
public interface EventAccessProxy extends EntityProxy {

    abstract Long getId();

    abstract Integer getVersion();

    abstract AccessRights getAccRights();

    abstract PersonProxy getPerson();

    abstract QuestionProxy getQuestion();

    abstract QuestionEventProxy getQuestionEvent();

    abstract void setId(Long id);

    abstract void setVersion(Integer version);

    abstract void setAccRights(AccessRights accRights);

    abstract void setPerson(PersonProxy person);

    abstract void setQuestion(QuestionProxy question);

    abstract void setQuestionEvent(QuestionEventProxy questionEvent);
}
