// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.Set;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.Person")
@ProxyForName("medizin.server.domain.Person")
public interface PersonProxy extends EntityProxy {

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);

    abstract String getName();

    abstract void setName(String name);

    abstract String getPrename();

    abstract void setPrename(String prename);

    abstract String getShidId();

    abstract void setShidId(String shidId);

    abstract String getEmail();

    abstract void setEmail(String email);

    abstract String getAlternativEmail();

    abstract void setAlternativEmail(String alternativEmail);

    abstract String getPhoneNumber();

    abstract void setPhoneNumber(String phoneNumber);

    abstract Boolean getIsAdmin();

    abstract void setIsAdmin(Boolean isAdmin);

    abstract Boolean getIsAccepted();

    abstract void setIsAccepted(Boolean isAccepted);

    abstract Set<medizin.client.managed.request.QuestionAccessProxy> getQuestionAccesses();

    abstract void setQuestionAccesses(Set<QuestionAccessProxy> questionAccesses);
}
