// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.QuestionType")
@ProxyForName("medizin.server.domain.QuestionType")
public interface QuestionTypeProxy extends EntityProxy {

    abstract String getQuestionTypeName();

    abstract void setQuestionTypeName(String questionTypeName);

    abstract Boolean getIsWeil();

    abstract void setIsWeil(Boolean isWeil);

    abstract Integer getTrueAnswers();

    abstract void setTrueAnswers(Integer trueAnswers);

    abstract Integer getFalseAnswers();

    abstract void setFalseAnswers(Integer falseAnswers);

    abstract Integer getSumAnswers();

    abstract void setSumAnswers(Integer sumAnswers);

    abstract Integer getMaxLetters();

    abstract void setMaxLetters(Integer maxLetters);

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);
}
