// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.QuestionEvent")
@ProxyForName("medizin.server.domain.QuestionEvent")
public interface QuestionEventProxy extends EntityProxy {

    abstract String getEventName();

    abstract void setEventName(String eventName);

    abstract InstitutionProxy getInstitution();

    abstract void setInstitution(InstitutionProxy institution);

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);
}
