// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.Set;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.QuestionTypeCountPerExam")
@ProxyForName("medizin.server.domain.QuestionTypeCountPerExam")
public interface QuestionTypeCountPerExamProxy extends EntityProxy {

    abstract Set<medizin.client.managed.request.QuestionTypeProxy> getQuestionTypesAssigned();

    abstract void setQuestionTypesAssigned(Set<QuestionTypeProxy> questionTypesAssigned);

    abstract AssesmentProxy getAssesment();

    abstract void setAssesment(AssesmentProxy assesment);

    abstract Integer getQuestionTypeCount();

    abstract void setQuestionTypeCount(Integer questionTypeCount);

    abstract Integer getSort_order();

    abstract void setSort_order(Integer sort_order);

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);
}
