// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.StaticToAssesment")
@ServiceName("medizin.server.domain.StaticToAssesment")
public interface StaticToAssesmentRequest extends RequestContext {

    abstract InstanceRequest<medizin.client.managed.request.StaticToAssesmentProxy, java.lang.Void> persist();

    abstract InstanceRequest<medizin.client.managed.request.StaticToAssesmentProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countStaticToAssesments();

    abstract Request<java.util.List<medizin.client.managed.request.StaticToAssesmentProxy>> findAllStaticToAssesments();

    abstract Request<medizin.client.managed.request.StaticToAssesmentProxy> findStaticToAssesment(Long id);

    abstract Request<java.util.List<medizin.client.managed.request.StaticToAssesmentProxy>> findStaticToAssesmentEntries(int firstResult, int maxResults);
}
