// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.lang.String;

privileged aspect StaticContent_Roo_JavaBean {
    
    public String StaticContent.getStaticText() {
        return this.staticText;
    }
    
    public void StaticContent.setStaticText(String staticText) {
        this.staticText = staticText;
    }
    
}
