// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;
import medizin.client.managed.request.AnswerProxy;
import medizin.client.managed.request.AnswerToAssQuestionProxy;
import medizin.client.managed.request.AssesmentQuestionProxy;
import medizin.client.scaffold.place.AbstractProxyListView;

public abstract class AnswerToAssQuestionListView_Roo_Gwt extends AbstractProxyListView<AnswerToAssQuestionProxy> {

    @UiField
    CellTable<AnswerToAssQuestionProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("sortOrder");
        table.addColumn(new TextColumn<AnswerToAssQuestionProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(AnswerToAssQuestionProxy object) {
                return renderer.render(object.getSortOrder());
            }
        }, "Sort Order");
        paths.add("answers");
        table.addColumn(new TextColumn<AnswerToAssQuestionProxy>() {

            Renderer<medizin.client.managed.request.AnswerProxy> renderer = medizin.client.managed.ui.AnswerProxyRenderer.instance();

            @Override
            public String getValue(AnswerToAssQuestionProxy object) {
                return renderer.render(object.getAnswers());
            }
        }, "Answers");
        paths.add("assesmentQuestion");
        table.addColumn(new TextColumn<AnswerToAssQuestionProxy>() {

            Renderer<medizin.client.managed.request.AssesmentQuestionProxy> renderer = medizin.client.managed.ui.AssesmentQuestionProxyRenderer.instance();

            @Override
            public String getValue(AnswerToAssQuestionProxy object) {
                return renderer.render(object.getAssesmentQuestion());
            }
        }, "Assesment Question");
        paths.add("id");
        table.addColumn(new TextColumn<AnswerToAssQuestionProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(AnswerToAssQuestionProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("version");
        table.addColumn(new TextColumn<AnswerToAssQuestionProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(AnswerToAssQuestionProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
    }
}
