// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.requestfactory.client.RequestFactoryEditorDriver;
import com.google.gwt.requestfactory.shared.RequestFactory;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import java.util.Collection;
import java.util.List;
import medizin.client.managed.activity.AnswerToAssQuestionEditActivityWrapper;
import medizin.client.managed.activity.AnswerToAssQuestionEditActivityWrapper.View;
import medizin.client.managed.request.AnswerProxy;
import medizin.client.managed.request.AnswerToAssQuestionProxy;
import medizin.client.managed.request.AssesmentQuestionProxy;
import medizin.client.scaffold.place.ProxyEditView;
import medizin.client.scaffold.ui.*;

public abstract class AnswerToAssQuestionMobileEditView_Roo_Gwt extends Composite implements View<AnswerToAssQuestionMobileEditView> {

    @UiField
    IntegerBox sortOrder;

    @UiField(provided = true)
    ValueListBox<AnswerProxy> answers = new ValueListBox<AnswerProxy>(medizin.client.managed.ui.AnswerProxyRenderer.instance(), new com.google.gwt.requestfactory.ui.client.EntityProxyKeyProvider<medizin.client.managed.request.AnswerProxy>());

    @UiField(provided = true)
    ValueListBox<AssesmentQuestionProxy> assesmentQuestion = new ValueListBox<AssesmentQuestionProxy>(medizin.client.managed.ui.AssesmentQuestionProxyRenderer.instance(), new com.google.gwt.requestfactory.ui.client.EntityProxyKeyProvider<medizin.client.managed.request.AssesmentQuestionProxy>());

    public void setAnswersPickerValues(Collection<AnswerProxy> values) {
        answers.setAcceptableValues(values);
    }

    public void setAssesmentQuestionPickerValues(Collection<AssesmentQuestionProxy> values) {
        assesmentQuestion.setAcceptableValues(values);
    }
}
