// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import java.util.Set;
import medizin.client.managed.request.AnswerToAssQuestionProxy;
import medizin.client.managed.request.AssesmentProxy;
import medizin.client.managed.request.AssesmentQuestionProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.scaffold.place.ProxyDetailsView;
import medizin.client.scaffold.place.ProxyListView;

public abstract class AssesmentQuestionDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<AssesmentQuestionProxy> {

    @UiField
    SpanElement dateAdded;

    @UiField
    SpanElement dateChanged;

    @UiField
    SpanElement rewiewer;

    @UiField
    SpanElement autor;

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    @UiField
    SpanElement orderAversion;

    @UiField
    SpanElement orderBversion;

    @UiField
    SpanElement trenschaerfe;

    @UiField
    SpanElement schwierigkeit;

    @UiField
    SpanElement isAssQuestionAcceptedRewiever;

    @UiField
    SpanElement isAssQuestionAcceptedAdmin;

    @UiField
    SpanElement isAssQuestionAdminProposal;

    @UiField
    SpanElement isAssQuestionAcceptedAutor;

    @UiField
    SpanElement question;

    @UiField
    SpanElement assesment;

    @UiField
    SpanElement answersToAssQuestion;

    AssesmentQuestionProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(AssesmentQuestionProxy proxy) {
        this.proxy = proxy;
        dateAdded.setInnerText(proxy.getDateAdded() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getDateAdded()));
        dateChanged.setInnerText(proxy.getDateChanged() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getDateChanged()));
        rewiewer.setInnerText(proxy.getRewiewer() == null ? "" : medizin.client.managed.ui.PersonProxyRenderer.instance().render(proxy.getRewiewer()));
        autor.setInnerText(proxy.getAutor() == null ? "" : medizin.client.managed.ui.PersonProxyRenderer.instance().render(proxy.getAutor()));
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        orderAversion.setInnerText(proxy.getOrderAversion() == null ? "" : String.valueOf(proxy.getOrderAversion()));
        orderBversion.setInnerText(proxy.getOrderBversion() == null ? "" : String.valueOf(proxy.getOrderBversion()));
        trenschaerfe.setInnerText(proxy.getTrenschaerfe() == null ? "" : String.valueOf(proxy.getTrenschaerfe()));
        schwierigkeit.setInnerText(proxy.getSchwierigkeit() == null ? "" : String.valueOf(proxy.getSchwierigkeit()));
        isAssQuestionAcceptedRewiever.setInnerText(proxy.getIsAssQuestionAcceptedRewiever() == null ? "" : String.valueOf(proxy.getIsAssQuestionAcceptedRewiever()));
        isAssQuestionAcceptedAdmin.setInnerText(proxy.getIsAssQuestionAcceptedAdmin() == null ? "" : String.valueOf(proxy.getIsAssQuestionAcceptedAdmin()));
        isAssQuestionAdminProposal.setInnerText(proxy.getIsAssQuestionAdminProposal() == null ? "" : String.valueOf(proxy.getIsAssQuestionAdminProposal()));
        isAssQuestionAcceptedAutor.setInnerText(proxy.getIsAssQuestionAcceptedAutor() == null ? "" : String.valueOf(proxy.getIsAssQuestionAcceptedAutor()));
        question.setInnerText(proxy.getQuestion() == null ? "" : medizin.client.managed.ui.QuestionProxyRenderer.instance().render(proxy.getQuestion()));
        assesment.setInnerText(proxy.getAssesment() == null ? "" : medizin.client.managed.ui.AssesmentProxyRenderer.instance().render(proxy.getAssesment()));
        answersToAssQuestion.setInnerText(proxy.getAnswersToAssQuestion() == null ? "" : medizin.client.scaffold.place.CollectionRenderer.of(medizin.client.managed.ui.AnswerToAssQuestionProxyRenderer.instance()).render(proxy.getAnswersToAssQuestion()));
        displayRenderer.setInnerText(medizin.client.managed.ui.AssesmentQuestionProxyRenderer.instance().render(proxy));
    }
}
