// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import medizin.client.managed.request.EventAccessProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionEventProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.scaffold.place.ProxyDetailsView;
import medizin.client.shared.AccessRights;

public abstract class EventAccessMobileDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<EventAccessProxy> {

    @UiField
    Element id;

    @UiField
    Element version;

    @UiField
    Element accRights;

    @UiField
    Element person;

    @UiField
    Element question;

    @UiField
    Element questionEvent;

    EventAccessProxy proxy;

    public void setValue(EventAccessProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        accRights.setInnerText(proxy.getAccRights() == null ? "" : String.valueOf(proxy.getAccRights()));
        person.setInnerText(proxy.getPerson() == null ? "" : medizin.client.managed.ui.PersonProxyRenderer.instance().render(proxy.getPerson()));
        question.setInnerText(proxy.getQuestion() == null ? "" : medizin.client.managed.ui.QuestionProxyRenderer.instance().render(proxy.getQuestion()));
        questionEvent.setInnerText(proxy.getQuestionEvent() == null ? "" : medizin.client.managed.ui.QuestionEventProxyRenderer.instance().render(proxy.getQuestionEvent()));
    }
}
