// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;
import medizin.client.managed.request.EventAccessProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionEventProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.scaffold.place.AbstractProxyListView;
import medizin.client.shared.AccessRights;

public abstract class EventAccessListView_Roo_Gwt extends AbstractProxyListView<EventAccessProxy> {

    @UiField
    CellTable<EventAccessProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<EventAccessProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(EventAccessProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("version");
        table.addColumn(new TextColumn<EventAccessProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(EventAccessProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
        paths.add("accRights");
        table.addColumn(new TextColumn<EventAccessProxy>() {

            Renderer<medizin.client.shared.AccessRights> renderer = new AbstractRenderer<medizin.client.shared.AccessRights>() {

                public String render(medizin.client.shared.AccessRights obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(EventAccessProxy object) {
                return renderer.render(object.getAccRights());
            }
        }, "Acc Rights");
        paths.add("person");
        table.addColumn(new TextColumn<EventAccessProxy>() {

            Renderer<medizin.client.managed.request.PersonProxy> renderer = medizin.client.managed.ui.PersonProxyRenderer.instance();

            @Override
            public String getValue(EventAccessProxy object) {
                return renderer.render(object.getPerson());
            }
        }, "Person");
        paths.add("question");
        table.addColumn(new TextColumn<EventAccessProxy>() {

            Renderer<medizin.client.managed.request.QuestionProxy> renderer = medizin.client.managed.ui.QuestionProxyRenderer.instance();

            @Override
            public String getValue(EventAccessProxy object) {
                return renderer.render(object.getQuestion());
            }
        }, "Question");
        paths.add("questionEvent");
        table.addColumn(new TextColumn<EventAccessProxy>() {

            Renderer<medizin.client.managed.request.QuestionEventProxy> renderer = medizin.client.managed.ui.QuestionEventProxyRenderer.instance();

            @Override
            public String getValue(EventAccessProxy object) {
                return renderer.render(object.getQuestionEvent());
            }
        }, "Question Event");
    }
}
