// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import medizin.client.managed.request.McProxy;

public class McProxyRenderer extends ProxyRenderer<McProxy> {

    private static medizin.client.managed.ui.McProxyRenderer INSTANCE;

    protected McProxyRenderer() {
        super(new String[] { "mcName" });
    }

    public static medizin.client.managed.ui.McProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new McProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(McProxy object) {
        if (object == null) {
            return "";
        }
        return object.getMcName() + " (" + object.getId() + ")";
    }
}
