// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import java.util.Set;
import medizin.client.managed.request.AnswerProxy;
import medizin.client.managed.request.CommentProxy;
import medizin.client.managed.request.KeywordProxy;
import medizin.client.managed.request.McProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionEventProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.managed.request.QuestionTypeProxy;

public class QuestionProxyRenderer extends ProxyRenderer<QuestionProxy> {

    private static medizin.client.managed.ui.QuestionProxyRenderer INSTANCE;

    protected QuestionProxyRenderer() {
        super(new String[] { "questionText" });
    }

    public static medizin.client.managed.ui.QuestionProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new QuestionProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(QuestionProxy object) {
        if (object == null) {
            return "";
        }
        return object.getQuestionText() + " (" + object.getId() + ")";
    }
}
