// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import java.util.Set;
import medizin.client.managed.request.AnswerProxy;
import medizin.client.managed.request.CommentProxy;
import medizin.client.managed.request.KeywordProxy;
import medizin.client.managed.request.McProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionEventProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.managed.request.QuestionTypeProxy;
import medizin.client.scaffold.place.ProxyDetailsView;

public abstract class QuestionMobileDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<QuestionProxy> {

    @UiField
    Element questionText;

    @UiField
    Element picturePath;

    @UiField
    Element questionVersion;

    @UiField
    Element isAcceptedRewiever;

    @UiField
    Element isAcceptedAdmin;

    @UiField
    Element isActive;

    @UiField
    Element previousVersion;

    @UiField
    Element keywords;

    @UiField
    Element questEvent;

    @UiField
    Element comment;

    @UiField
    Element questionType;

    @UiField
    Element mcs;

    @UiField
    Element answers;

    @UiField
    Element dateAdded;

    @UiField
    Element dateChanged;

    @UiField
    Element rewiewer;

    @UiField
    Element autor;

    @UiField
    Element id;

    @UiField
    Element version;

    QuestionProxy proxy;

    public void setValue(QuestionProxy proxy) {
        this.proxy = proxy;
        questionText.setInnerText(proxy.getQuestionText() == null ? "" : String.valueOf(proxy.getQuestionText()));
        picturePath.setInnerText(proxy.getPicturePath() == null ? "" : String.valueOf(proxy.getPicturePath()));
        questionVersion.setInnerText(proxy.getQuestionVersion() == null ? "" : String.valueOf(proxy.getQuestionVersion()));
        isAcceptedRewiever.setInnerText(proxy.getIsAcceptedRewiever() == null ? "" : String.valueOf(proxy.getIsAcceptedRewiever()));
        isAcceptedAdmin.setInnerText(proxy.getIsAcceptedAdmin() == null ? "" : String.valueOf(proxy.getIsAcceptedAdmin()));
        isActive.setInnerText(proxy.getIsActive() == null ? "" : String.valueOf(proxy.getIsActive()));
        previousVersion.setInnerText(proxy.getPreviousVersion() == null ? "" : medizin.client.managed.ui.QuestionProxyRenderer.instance().render(proxy.getPreviousVersion()));
        keywords.setInnerText(proxy.getKeywords() == null ? "" : medizin.client.scaffold.place.CollectionRenderer.of(medizin.client.managed.ui.KeywordProxyRenderer.instance()).render(proxy.getKeywords()));
        questEvent.setInnerText(proxy.getQuestEvent() == null ? "" : medizin.client.managed.ui.QuestionEventProxyRenderer.instance().render(proxy.getQuestEvent()));
        comment.setInnerText(proxy.getComment() == null ? "" : medizin.client.managed.ui.CommentProxyRenderer.instance().render(proxy.getComment()));
        questionType.setInnerText(proxy.getQuestionType() == null ? "" : medizin.client.managed.ui.QuestionTypeProxyRenderer.instance().render(proxy.getQuestionType()));
        mcs.setInnerText(proxy.getMcs() == null ? "" : medizin.client.scaffold.place.CollectionRenderer.of(medizin.client.managed.ui.McProxyRenderer.instance()).render(proxy.getMcs()));
        answers.setInnerText(proxy.getAnswers() == null ? "" : medizin.client.scaffold.place.CollectionRenderer.of(medizin.client.managed.ui.AnswerProxyRenderer.instance()).render(proxy.getAnswers()));
        dateAdded.setInnerText(proxy.getDateAdded() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getDateAdded()));
        dateChanged.setInnerText(proxy.getDateChanged() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getDateChanged()));
        rewiewer.setInnerText(proxy.getRewiewer() == null ? "" : medizin.client.managed.ui.PersonProxyRenderer.instance().render(proxy.getRewiewer()));
        autor.setInnerText(proxy.getAutor() == null ? "" : medizin.client.managed.ui.PersonProxyRenderer.instance().render(proxy.getAutor()));
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
    }
}
