// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.requestfactory.client.RequestFactoryEditorDriver;
import com.google.gwt.requestfactory.shared.RequestFactory;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import java.util.Collection;
import java.util.List;
import java.util.Set;
import medizin.client.managed.activity.QuestionEditActivityWrapper;
import medizin.client.managed.activity.QuestionEditActivityWrapper.View;
import medizin.client.managed.request.AnswerProxy;
import medizin.client.managed.request.CommentProxy;
import medizin.client.managed.request.KeywordProxy;
import medizin.client.managed.request.McProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionEventProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.managed.request.QuestionTypeProxy;
import medizin.client.scaffold.place.ProxyEditView;
import medizin.client.scaffold.ui.*;

public abstract class QuestionMobileEditView_Roo_Gwt extends Composite implements View<QuestionMobileEditView> {

    @UiField
    TextBox questionText;

    @UiField
    TextBox picturePath;

    @UiField
    DoubleBox questionVersion;

    @UiField(provided = true)
    CheckBox isAcceptedRewiever = new CheckBox() {

        public void setValue(Boolean value) {
            super.setValue(value == null ? Boolean.FALSE : value);
        }
    };

    @UiField(provided = true)
    CheckBox isAcceptedAdmin = new CheckBox() {

        public void setValue(Boolean value) {
            super.setValue(value == null ? Boolean.FALSE : value);
        }
    };

    @UiField(provided = true)
    CheckBox isActive = new CheckBox() {

        public void setValue(Boolean value) {
            super.setValue(value == null ? Boolean.FALSE : value);
        }
    };

    @UiField(provided = true)
    ValueListBox<QuestionProxy> previousVersion = new ValueListBox<QuestionProxy>(medizin.client.managed.ui.QuestionProxyRenderer.instance(), new com.google.gwt.requestfactory.ui.client.EntityProxyKeyProvider<medizin.client.managed.request.QuestionProxy>());

    @UiField
    KeywordSetEditor keywords;

    @UiField(provided = true)
    ValueListBox<QuestionEventProxy> questEvent = new ValueListBox<QuestionEventProxy>(medizin.client.managed.ui.QuestionEventProxyRenderer.instance(), new com.google.gwt.requestfactory.ui.client.EntityProxyKeyProvider<medizin.client.managed.request.QuestionEventProxy>());

    @UiField(provided = true)
    ValueListBox<CommentProxy> comment = new ValueListBox<CommentProxy>(medizin.client.managed.ui.CommentProxyRenderer.instance(), new com.google.gwt.requestfactory.ui.client.EntityProxyKeyProvider<medizin.client.managed.request.CommentProxy>());

    @UiField(provided = true)
    ValueListBox<QuestionTypeProxy> questionType = new ValueListBox<QuestionTypeProxy>(medizin.client.managed.ui.QuestionTypeProxyRenderer.instance(), new com.google.gwt.requestfactory.ui.client.EntityProxyKeyProvider<medizin.client.managed.request.QuestionTypeProxy>());

    @UiField
    McSetEditor mcs;

    @UiField
    AnswerSetEditor answers;

    @UiField
    DateBox dateAdded;

    @UiField
    DateBox dateChanged;

    @UiField(provided = true)
    ValueListBox<PersonProxy> rewiewer = new ValueListBox<PersonProxy>(medizin.client.managed.ui.PersonProxyRenderer.instance(), new com.google.gwt.requestfactory.ui.client.EntityProxyKeyProvider<medizin.client.managed.request.PersonProxy>());

    @UiField(provided = true)
    ValueListBox<PersonProxy> autor = new ValueListBox<PersonProxy>(medizin.client.managed.ui.PersonProxyRenderer.instance(), new com.google.gwt.requestfactory.ui.client.EntityProxyKeyProvider<medizin.client.managed.request.PersonProxy>());

    public void setAnswersPickerValues(Collection<AnswerProxy> values) {
        answers.setAcceptableValues(values);
    }

    public void setRewiewerPickerValues(Collection<PersonProxy> values) {
        rewiewer.setAcceptableValues(values);
    }

    public void setQuestEventPickerValues(Collection<QuestionEventProxy> values) {
        questEvent.setAcceptableValues(values);
    }

    public void setAutorPickerValues(Collection<PersonProxy> values) {
        autor.setAcceptableValues(values);
    }

    public void setCommentPickerValues(Collection<CommentProxy> values) {
        comment.setAcceptableValues(values);
    }

    public void setQuestionTypePickerValues(Collection<QuestionTypeProxy> values) {
        questionType.setAcceptableValues(values);
    }

    public void setKeywordsPickerValues(Collection<KeywordProxy> values) {
        keywords.setAcceptableValues(values);
    }

    public void setMcsPickerValues(Collection<McProxy> values) {
        mcs.setAcceptableValues(values);
    }

    public void setPreviousVersionPickerValues(Collection<QuestionProxy> values) {
        previousVersion.setAcceptableValues(values);
    }
}
