// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;
import medizin.client.managed.request.AssesmentProxy;
import medizin.client.managed.request.StaticContentProxy;
import medizin.client.managed.request.StaticToAssesmentProxy;
import medizin.client.scaffold.place.AbstractProxyListView;

public abstract class StaticToAssesmentListView_Roo_Gwt extends AbstractProxyListView<StaticToAssesmentProxy> {

    @UiField
    CellTable<StaticToAssesmentProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<StaticToAssesmentProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(StaticToAssesmentProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("version");
        table.addColumn(new TextColumn<StaticToAssesmentProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(StaticToAssesmentProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
        paths.add("sortOrder");
        table.addColumn(new TextColumn<StaticToAssesmentProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(StaticToAssesmentProxy object) {
                return renderer.render(object.getSortOrder());
            }
        }, "Sort Order");
        paths.add("staticContent");
        table.addColumn(new TextColumn<StaticToAssesmentProxy>() {

            Renderer<medizin.client.managed.request.StaticContentProxy> renderer = medizin.client.managed.ui.StaticContentProxyRenderer.instance();

            @Override
            public String getValue(StaticToAssesmentProxy object) {
                return renderer.render(object.getStaticContent());
            }
        }, "Static Content");
        paths.add("assesment");
        table.addColumn(new TextColumn<StaticToAssesmentProxy>() {

            Renderer<medizin.client.managed.request.AssesmentProxy> renderer = medizin.client.managed.ui.AssesmentProxyRenderer.instance();

            @Override
            public String getValue(StaticToAssesmentProxy object) {
                return renderer.render(object.getAssesment());
            }
        }, "Assesment");
    }
}
