// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import medizin.client.managed.request.AssesmentProxy;
import medizin.client.managed.request.StaticContentProxy;
import medizin.client.managed.request.StaticToAssesmentProxy;

public class StaticToAssesmentProxyRenderer extends ProxyRenderer<StaticToAssesmentProxy> {

    private static medizin.client.managed.ui.StaticToAssesmentProxyRenderer INSTANCE;

    protected StaticToAssesmentProxyRenderer() {
        super(new String[] { "id" });
    }

    public static medizin.client.managed.ui.StaticToAssesmentProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new StaticToAssesmentProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(StaticToAssesmentProxy object) {
        if (object == null) {
            return "";
        }
        return object.getId() + " (" + object.getId() + ")";
    }
}
