// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import medizin.client.managed.request.AnswerProxy;
import medizin.client.managed.request.AnswerToAssQuestionProxy;
import medizin.client.managed.request.ApplicationEntityTypesProcessor;
import medizin.client.managed.request.ApplicationRequestFactory;
import medizin.client.managed.request.AssesmentProxy;
import medizin.client.managed.request.AssesmentQuestionProxy;
import medizin.client.managed.request.CommentProxy;
import medizin.client.managed.request.InstitutionProxy;
import medizin.client.managed.request.KeywordProxy;
import medizin.client.managed.request.McProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionAccessProxy;
import medizin.client.managed.request.QuestionEventProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.managed.request.QuestionSumPerPersonProxy;
import medizin.client.managed.request.QuestionTypeCountPerExamProxy;
import medizin.client.managed.request.QuestionTypeProxy;
import medizin.client.managed.request.StaticContentProxy;
import medizin.client.managed.request.StaticToAssesmentProxy;
import medizin.client.managed.ui.AnswerListView;
import medizin.client.managed.ui.AnswerMobileListView;
import medizin.client.managed.ui.AnswerToAssQuestionListView;
import medizin.client.managed.ui.AnswerToAssQuestionMobileListView;
import medizin.client.managed.ui.AssesmentListView;
import medizin.client.managed.ui.AssesmentMobileListView;
import medizin.client.managed.ui.AssesmentQuestionListView;
import medizin.client.managed.ui.AssesmentQuestionMobileListView;
import medizin.client.managed.ui.CommentListView;
import medizin.client.managed.ui.CommentMobileListView;
import medizin.client.managed.ui.InstitutionListView;
import medizin.client.managed.ui.InstitutionMobileListView;
import medizin.client.managed.ui.KeywordListView;
import medizin.client.managed.ui.KeywordMobileListView;
import medizin.client.managed.ui.McListView;
import medizin.client.managed.ui.McMobileListView;
import medizin.client.managed.ui.PersonListView;
import medizin.client.managed.ui.PersonMobileListView;
import medizin.client.managed.ui.QuestionAccessListView;
import medizin.client.managed.ui.QuestionAccessMobileListView;
import medizin.client.managed.ui.QuestionEventListView;
import medizin.client.managed.ui.QuestionEventMobileListView;
import medizin.client.managed.ui.QuestionListView;
import medizin.client.managed.ui.QuestionMobileListView;
import medizin.client.managed.ui.QuestionSumPerPersonListView;
import medizin.client.managed.ui.QuestionSumPerPersonMobileListView;
import medizin.client.managed.ui.QuestionTypeCountPerExamListView;
import medizin.client.managed.ui.QuestionTypeCountPerExamMobileListView;
import medizin.client.managed.ui.QuestionTypeListView;
import medizin.client.managed.ui.QuestionTypeMobileListView;
import medizin.client.managed.ui.StaticContentListView;
import medizin.client.managed.ui.StaticContentMobileListView;
import medizin.client.managed.ui.StaticToAssesmentListView;
import medizin.client.managed.ui.StaticToAssesmentMobileListView;
import medizin.client.scaffold.ScaffoldApp;
import medizin.client.scaffold.place.ProxyListPlace;

public final class ApplicationMasterActivities extends ApplicationMasterActivities_Roo_Gwt {

    @Inject
    public ApplicationMasterActivities(ApplicationRequestFactory requests, PlaceController placeController) {
        this.requests = requests;
        this.placeController = placeController;
    }
}
