// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.RequestContext;
import medizin.client.managed.request.ApplicationRequestFactory;
import medizin.client.managed.request.AssesmentProxy;
import medizin.client.managed.request.AssesmentRequest;
import medizin.client.managed.request.McProxy;
import medizin.client.managed.ui.AssesmentDetailsView;
import medizin.client.managed.ui.AssesmentEditView;
import medizin.client.managed.ui.AssesmentListView;
import medizin.client.managed.ui.AssesmentMobileDetailsView;
import medizin.client.managed.ui.AssesmentMobileEditView;
import medizin.client.scaffold.ScaffoldApp;
import medizin.client.scaffold.place.CreateAndEditProxy;
import medizin.client.scaffold.place.FindAndEditProxy;
import medizin.client.scaffold.place.ProxyPlace;

public class AssesmentActivitiesMapper {

    private final ApplicationRequestFactory requests;

    private final PlaceController placeController;

    public AssesmentActivitiesMapper(ApplicationRequestFactory requests, PlaceController placeController) {
        this.requests = requests;
        this.placeController = placeController;
    }

    public Activity getActivity(ProxyPlace place) {
        switch(place.getOperation()) {
            case DETAILS:
                return new AssesmentDetailsActivity((EntityProxyId<AssesmentProxy>) place.getProxyId(), requests, placeController, ScaffoldApp.isMobile() ? AssesmentMobileDetailsView.instance() : AssesmentDetailsView.instance());
            case EDIT:
                return makeEditActivity(place);
            case CREATE:
                return makeCreateActivity();
        }
        throw new IllegalArgumentException("Unknown operation " + place.getOperation());
    }

    @SuppressWarnings("unchecked")
    private EntityProxyId<medizin.client.managed.request.AssesmentProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<AssesmentProxy>) place.getProxyId();
    }

    private Activity makeCreateActivity() {
        AssesmentEditView.instance().setCreating(true);
        final AssesmentRequest request = requests.assesmentRequest();
        Activity activity = new CreateAndEditProxy<AssesmentProxy>(AssesmentProxy.class, request, ScaffoldApp.isMobile() ? AssesmentMobileEditView.instance() : AssesmentEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(AssesmentProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new AssesmentEditActivityWrapper(requests, ScaffoldApp.isMobile() ? AssesmentMobileEditView.instance() : AssesmentEditView.instance(), activity, null);
    }

    private Activity makeEditActivity(ProxyPlace place) {
        AssesmentEditView.instance().setCreating(false);
        EntityProxyId<AssesmentProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<AssesmentProxy>(proxyId, requests, ScaffoldApp.isMobile() ? AssesmentMobileEditView.instance() : AssesmentEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(AssesmentProxy proxy) {
                AssesmentRequest request = requests.assesmentRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new AssesmentEditActivityWrapper(requests, ScaffoldApp.isMobile() ? AssesmentMobileEditView.instance() : AssesmentEditView.instance(), activity, proxyId);
    }
}
