// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.RequestContext;
import medizin.client.managed.request.ApplicationRequestFactory;
import medizin.client.managed.request.McProxy;
import medizin.client.managed.request.McRequest;
import medizin.client.managed.ui.McDetailsView;
import medizin.client.managed.ui.McEditView;
import medizin.client.managed.ui.McListView;
import medizin.client.managed.ui.McMobileDetailsView;
import medizin.client.managed.ui.McMobileEditView;
import medizin.client.scaffold.ScaffoldApp;
import medizin.client.scaffold.place.CreateAndEditProxy;
import medizin.client.scaffold.place.FindAndEditProxy;
import medizin.client.scaffold.place.ProxyPlace;

public class McActivitiesMapper {

    private final ApplicationRequestFactory requests;

    private final PlaceController placeController;

    public McActivitiesMapper(ApplicationRequestFactory requests, PlaceController placeController) {
        this.requests = requests;
        this.placeController = placeController;
    }

    public Activity getActivity(ProxyPlace place) {
        switch(place.getOperation()) {
            case DETAILS:
                return new McDetailsActivity((EntityProxyId<McProxy>) place.getProxyId(), requests, placeController, ScaffoldApp.isMobile() ? McMobileDetailsView.instance() : McDetailsView.instance());
            case EDIT:
                return makeEditActivity(place);
            case CREATE:
                return makeCreateActivity();
        }
        throw new IllegalArgumentException("Unknown operation " + place.getOperation());
    }

    @SuppressWarnings("unchecked")
    private EntityProxyId<medizin.client.managed.request.McProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<McProxy>) place.getProxyId();
    }

    private Activity makeCreateActivity() {
        McEditView.instance().setCreating(true);
        final McRequest request = requests.mcRequest();
        Activity activity = new CreateAndEditProxy<McProxy>(McProxy.class, request, ScaffoldApp.isMobile() ? McMobileEditView.instance() : McEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(McProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new McEditActivityWrapper(requests, ScaffoldApp.isMobile() ? McMobileEditView.instance() : McEditView.instance(), activity, null);
    }

    private Activity makeEditActivity(ProxyPlace place) {
        McEditView.instance().setCreating(false);
        EntityProxyId<McProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<McProxy>(proxyId, requests, ScaffoldApp.isMobile() ? McMobileEditView.instance() : McEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(McProxy proxy) {
                McRequest request = requests.mcRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new McEditActivityWrapper(requests, ScaffoldApp.isMobile() ? McMobileEditView.instance() : McEditView.instance(), activity, proxyId);
    }
}
