// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.RequestContext;
import java.util.Set;
import medizin.client.managed.request.ApplicationRequestFactory;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.PersonRequest;
import medizin.client.managed.request.QuestionAccessProxy;
import medizin.client.managed.ui.PersonDetailsView;
import medizin.client.managed.ui.PersonEditView;
import medizin.client.managed.ui.PersonListView;
import medizin.client.managed.ui.PersonMobileDetailsView;
import medizin.client.managed.ui.PersonMobileEditView;
import medizin.client.managed.ui.QuestionAccessSetEditor;
import medizin.client.scaffold.ScaffoldApp;
import medizin.client.scaffold.place.CreateAndEditProxy;
import medizin.client.scaffold.place.FindAndEditProxy;
import medizin.client.scaffold.place.ProxyPlace;

public class PersonActivitiesMapper {

    private final ApplicationRequestFactory requests;

    private final PlaceController placeController;

    public PersonActivitiesMapper(ApplicationRequestFactory requests, PlaceController placeController) {
        this.requests = requests;
        this.placeController = placeController;
    }

    public Activity getActivity(ProxyPlace place) {
        switch(place.getOperation()) {
            case DETAILS:
                return new PersonDetailsActivity((EntityProxyId<PersonProxy>) place.getProxyId(), requests, placeController, ScaffoldApp.isMobile() ? PersonMobileDetailsView.instance() : PersonDetailsView.instance());
            case EDIT:
                return makeEditActivity(place);
            case CREATE:
                return makeCreateActivity();
        }
        throw new IllegalArgumentException("Unknown operation " + place.getOperation());
    }

    @SuppressWarnings("unchecked")
    private EntityProxyId<medizin.client.managed.request.PersonProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<PersonProxy>) place.getProxyId();
    }

    private Activity makeCreateActivity() {
        PersonEditView.instance().setCreating(true);
        final PersonRequest request = requests.personRequest();
        Activity activity = new CreateAndEditProxy<PersonProxy>(PersonProxy.class, request, ScaffoldApp.isMobile() ? PersonMobileEditView.instance() : PersonEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(PersonProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new PersonEditActivityWrapper(requests, ScaffoldApp.isMobile() ? PersonMobileEditView.instance() : PersonEditView.instance(), activity, null);
    }

    private Activity makeEditActivity(ProxyPlace place) {
        PersonEditView.instance().setCreating(false);
        EntityProxyId<PersonProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<PersonProxy>(proxyId, requests, ScaffoldApp.isMobile() ? PersonMobileEditView.instance() : PersonEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(PersonProxy proxy) {
                PersonRequest request = requests.personRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new PersonEditActivityWrapper(requests, ScaffoldApp.isMobile() ? PersonMobileEditView.instance() : PersonEditView.instance(), activity, proxyId);
    }
}
