// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.RequestContext;
import java.util.Set;
import medizin.client.managed.request.ApplicationRequestFactory;
import medizin.client.managed.request.AssesmentProxy;
import medizin.client.managed.request.QuestionTypeCountPerExamProxy;
import medizin.client.managed.request.QuestionTypeCountPerExamRequest;
import medizin.client.managed.request.QuestionTypeProxy;
import medizin.client.managed.ui.QuestionTypeCountPerExamDetailsView;
import medizin.client.managed.ui.QuestionTypeCountPerExamEditView;
import medizin.client.managed.ui.QuestionTypeCountPerExamListView;
import medizin.client.managed.ui.QuestionTypeCountPerExamMobileDetailsView;
import medizin.client.managed.ui.QuestionTypeCountPerExamMobileEditView;
import medizin.client.managed.ui.QuestionTypeSetEditor;
import medizin.client.scaffold.ScaffoldApp;
import medizin.client.scaffold.place.CreateAndEditProxy;
import medizin.client.scaffold.place.FindAndEditProxy;
import medizin.client.scaffold.place.ProxyPlace;

public class QuestionTypeCountPerExamActivitiesMapper {

    private final ApplicationRequestFactory requests;

    private final PlaceController placeController;

    public QuestionTypeCountPerExamActivitiesMapper(ApplicationRequestFactory requests, PlaceController placeController) {
        this.requests = requests;
        this.placeController = placeController;
    }

    public Activity getActivity(ProxyPlace place) {
        switch(place.getOperation()) {
            case DETAILS:
                return new QuestionTypeCountPerExamDetailsActivity((EntityProxyId<QuestionTypeCountPerExamProxy>) place.getProxyId(), requests, placeController, ScaffoldApp.isMobile() ? QuestionTypeCountPerExamMobileDetailsView.instance() : QuestionTypeCountPerExamDetailsView.instance());
            case EDIT:
                return makeEditActivity(place);
            case CREATE:
                return makeCreateActivity();
        }
        throw new IllegalArgumentException("Unknown operation " + place.getOperation());
    }

    @SuppressWarnings("unchecked")
    private EntityProxyId<medizin.client.managed.request.QuestionTypeCountPerExamProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<QuestionTypeCountPerExamProxy>) place.getProxyId();
    }

    private Activity makeCreateActivity() {
        QuestionTypeCountPerExamEditView.instance().setCreating(true);
        final QuestionTypeCountPerExamRequest request = requests.questionTypeCountPerExamRequest();
        Activity activity = new CreateAndEditProxy<QuestionTypeCountPerExamProxy>(QuestionTypeCountPerExamProxy.class, request, ScaffoldApp.isMobile() ? QuestionTypeCountPerExamMobileEditView.instance() : QuestionTypeCountPerExamEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(QuestionTypeCountPerExamProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new QuestionTypeCountPerExamEditActivityWrapper(requests, ScaffoldApp.isMobile() ? QuestionTypeCountPerExamMobileEditView.instance() : QuestionTypeCountPerExamEditView.instance(), activity, null);
    }

    private Activity makeEditActivity(ProxyPlace place) {
        QuestionTypeCountPerExamEditView.instance().setCreating(false);
        EntityProxyId<QuestionTypeCountPerExamProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<QuestionTypeCountPerExamProxy>(proxyId, requests, ScaffoldApp.isMobile() ? QuestionTypeCountPerExamMobileEditView.instance() : QuestionTypeCountPerExamEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(QuestionTypeCountPerExamProxy proxy) {
                QuestionTypeCountPerExamRequest request = requests.questionTypeCountPerExamRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new QuestionTypeCountPerExamEditActivityWrapper(requests, ScaffoldApp.isMobile() ? QuestionTypeCountPerExamMobileEditView.instance() : QuestionTypeCountPerExamEditView.instance(), activity, proxyId);
    }
}
