// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.safehtml.shared.SafeHtml;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.safehtml.shared.SafeHtmlUtils;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.AbstractSafeHtmlRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.text.shared.SafeHtmlRenderer;
import java.util.HashSet;
import java.util.Set;
import medizin.client.managed.request.AnswerProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.scaffold.ScaffoldMobileApp;
import medizin.client.scaffold.ui.MobileProxyListView;
import medizin.client.shared.Validity;

public abstract class AnswerMobileListView_Roo_Gwt extends MobileProxyListView<AnswerProxy> {

    protected Set<String> paths = new HashSet<String>();

    public AnswerMobileListView_Roo_Gwt(String buttonText, SafeHtmlRenderer<medizin.client.managed.request.AnswerProxy> renderer) {
        super(buttonText, renderer);
    }

    public void init() {
        paths.add("answerText");
        paths.add("picturePath");
        paths.add("dateAdded");
    }
}
