// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import medizin.client.managed.request.AnswerProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.shared.Validity;

public class AnswerProxyRenderer extends ProxyRenderer<AnswerProxy> {

    private static medizin.client.managed.ui.AnswerProxyRenderer INSTANCE;

    protected AnswerProxyRenderer() {
        super(new String[] { "answerText" });
    }

    public static medizin.client.managed.ui.AnswerProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new AnswerProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(AnswerProxy object) {
        if (object == null) {
            return "";
        }
        return object.getAnswerText() + " (" + object.getId() + ")";
    }
}
