// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import java.util.Set;
import medizin.client.managed.request.AnswerToAssQuestionProxy;
import medizin.client.managed.request.AssesmentProxy;
import medizin.client.managed.request.AssesmentQuestionProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionProxy;

public class AssesmentQuestionProxyRenderer extends ProxyRenderer<AssesmentQuestionProxy> {

    private static medizin.client.managed.ui.AssesmentQuestionProxyRenderer INSTANCE;

    protected AssesmentQuestionProxyRenderer() {
        super(new String[] { "id" });
    }

    public static medizin.client.managed.ui.AssesmentQuestionProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new AssesmentQuestionProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(AssesmentQuestionProxy object) {
        if (object == null) {
            return "";
        }
        return object.getId() + " (" + object.getId() + ")";
    }
}
