// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import medizin.client.managed.request.AssesmentProxy;
import medizin.client.managed.request.McProxy;

public class AssesmentProxyRenderer extends ProxyRenderer<AssesmentProxy> {

    private static medizin.client.managed.ui.AssesmentProxyRenderer INSTANCE;

    protected AssesmentProxyRenderer() {
        super(new String[] { "name" });
    }

    public static medizin.client.managed.ui.AssesmentProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new AssesmentProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(AssesmentProxy object) {
        if (object == null) {
            return "";
        }
        return object.getName() + " (" + object.getId() + ")";
    }
}
