// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import medizin.client.managed.request.AssesmentProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionEventProxy;
import medizin.client.managed.request.QuestionSumPerPersonProxy;
import medizin.client.scaffold.place.ProxyDetailsView;

public abstract class QuestionSumPerPersonMobileDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<QuestionSumPerPersonProxy> {

    @UiField
    Element responsiblePerson;

    @UiField
    Element questionEvent;

    @UiField
    Element assesment;

    @UiField
    Element questionSum;

    @UiField
    Element sort_order;

    @UiField
    Element id;

    @UiField
    Element version;

    QuestionSumPerPersonProxy proxy;

    public void setValue(QuestionSumPerPersonProxy proxy) {
        this.proxy = proxy;
        responsiblePerson.setInnerText(proxy.getResponsiblePerson() == null ? "" : medizin.client.managed.ui.PersonProxyRenderer.instance().render(proxy.getResponsiblePerson()));
        questionEvent.setInnerText(proxy.getQuestionEvent() == null ? "" : medizin.client.managed.ui.QuestionEventProxyRenderer.instance().render(proxy.getQuestionEvent()));
        assesment.setInnerText(proxy.getAssesment() == null ? "" : medizin.client.managed.ui.AssesmentProxyRenderer.instance().render(proxy.getAssesment()));
        questionSum.setInnerText(proxy.getQuestionSum() == null ? "" : String.valueOf(proxy.getQuestionSum()));
        sort_order.setInnerText(proxy.getSort_order() == null ? "" : String.valueOf(proxy.getSort_order()));
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
    }
}
