// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import medizin.client.managed.request.QuestionTypeProxy;

public class QuestionTypeProxyRenderer extends ProxyRenderer<QuestionTypeProxy> {

    private static medizin.client.managed.ui.QuestionTypeProxyRenderer INSTANCE;

    protected QuestionTypeProxyRenderer() {
        super(new String[] { "questionTypeName" });
    }

    public static medizin.client.managed.ui.QuestionTypeProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new QuestionTypeProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(QuestionTypeProxy object) {
        if (object == null) {
            return "";
        }
        return object.getQuestionTypeName() + " (" + object.getId() + ")";
    }
}
