// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import medizin.client.managed.request.StaticContentProxy;

public class StaticContentProxyRenderer extends ProxyRenderer<StaticContentProxy> {

    private static medizin.client.managed.ui.StaticContentProxyRenderer INSTANCE;

    protected StaticContentProxyRenderer() {
        super(new String[] { "staticText" });
    }

    public static medizin.client.managed.ui.StaticContentProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new StaticContentProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(StaticContentProxy object) {
        if (object == null) {
            return "";
        }
        return object.getStaticText() + " (" + object.getId() + ")";
    }
}
