// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.lang.String;

privileged aspect Mc_Roo_JavaBean {
    
    public String Mc.getMcName() {
        return this.mcName;
    }
    
    public void Mc.setMcName(String mcName) {
        this.mcName = mcName;
    }
    
}
