// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.lang.String;

privileged aspect Mc_Roo_ToString {
    
    public String Mc.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("McName: ").append(getMcName());
        return sb.toString();
    }
    
}
