// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.activity;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.view.client.Range;
import java.util.List;
import medizin.client.managed.request.AnswerProxy;
import medizin.client.managed.request.ApplicationRequestFactory;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.scaffold.ScaffoldMobileApp;
import medizin.client.scaffold.activity.IsScaffoldMobileActivity;
import medizin.client.scaffold.place.AbstractProxyListActivity;
import medizin.client.scaffold.place.ProxyListView;
import medizin.client.shared.Validity;
/**
 * Activity for handling AnswerListViews.
 * @author masterthesis
 *
 */
public class AnswerListActivity extends AbstractProxyListActivity<AnswerProxy> implements IsScaffoldMobileActivity {

    private final ApplicationRequestFactory requests;

    public AnswerListActivity(ApplicationRequestFactory requests, ProxyListView<medizin.client.managed.request.AnswerProxy> view, PlaceController placeController) {
        super(placeController, view, AnswerProxy.class);
        this.requests = requests;
    }

    public Place getBackButtonPlace() {
        return ScaffoldMobileApp.ROOT_PLACE;
    }

    public String getBackButtonText() {
        return "Entities";
    }

    public Place getEditButtonPlace() {
        return null;
    }

    public String getTitleText() {
        return "Answers";
    }

    public boolean hasEditButton() {
        return false;
    }

    protected Request<java.util.List<medizin.client.managed.request.AnswerProxy>> createRangeRequest(Range range) {
        return requests.answerRequest().findAnswerEntries(range.getStart(), range.getLength());
    }

    protected void fireCountRequest(Receiver<Long> callback) {
        requests.answerRequest().countAnswers().fire(callback);
    }
}
