// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import medizin.client.managed.activity.AssesmentQuestionEditActivityWrapper.View;
import medizin.client.managed.request.AnswerToAssQuestionProxy;
import medizin.client.managed.request.ApplicationRequestFactory;
import medizin.client.managed.request.AssesmentProxy;
import medizin.client.managed.request.AssesmentQuestionProxy;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.managed.ui.AnswerToAssQuestionSetEditor;
import medizin.client.scaffold.activity.IsScaffoldMobileActivity;
import medizin.client.scaffold.place.ProxyEditView;
import medizin.client.scaffold.place.ProxyListPlace;
import medizin.client.scaffold.place.ProxyPlace;

public abstract class AssesmentQuestionEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setRewiewerPickerValues(Collections.<PersonProxy>emptyList());
        requests.personRequest().findPersonEntries(0, 50).with(medizin.client.managed.ui.PersonProxyRenderer.instance().getPaths()).fire(new Receiver<List<PersonProxy>>() {

            public void onSuccess(List<PersonProxy> response) {
                List<PersonProxy> values = new ArrayList<PersonProxy>();
                values.add(null);
                values.addAll(response);
                view.setRewiewerPickerValues(values);
            }
        });
        view.setAutorPickerValues(Collections.<PersonProxy>emptyList());
        requests.personRequest().findPersonEntries(0, 50).with(medizin.client.managed.ui.PersonProxyRenderer.instance().getPaths()).fire(new Receiver<List<PersonProxy>>() {

            public void onSuccess(List<PersonProxy> response) {
                List<PersonProxy> values = new ArrayList<PersonProxy>();
                values.add(null);
                values.addAll(response);
                view.setAutorPickerValues(values);
            }
        });
        view.setQuestionPickerValues(Collections.<QuestionProxy>emptyList());
        requests.questionRequest().findQuestionEntries(0, 50).with(medizin.client.managed.ui.QuestionProxyRenderer.instance().getPaths()).fire(new Receiver<List<QuestionProxy>>() {

            public void onSuccess(List<QuestionProxy> response) {
                List<QuestionProxy> values = new ArrayList<QuestionProxy>();
                values.add(null);
                values.addAll(response);
                view.setQuestionPickerValues(values);
            }
        });
        view.setAssesmentPickerValues(Collections.<AssesmentProxy>emptyList());
        requests.assesmentRequest().findAssesmentEntries(0, 50).with(medizin.client.managed.ui.AssesmentProxyRenderer.instance().getPaths()).fire(new Receiver<List<AssesmentProxy>>() {

            public void onSuccess(List<AssesmentProxy> response) {
                List<AssesmentProxy> values = new ArrayList<AssesmentProxy>();
                values.add(null);
                values.addAll(response);
                view.setAssesmentPickerValues(values);
            }
        });
        view.setAnswersToAssQuestionPickerValues(Collections.<AnswerToAssQuestionProxy>emptyList());
        requests.answerToAssQuestionRequest().findAnswerToAssQuestionEntries(0, 50).with(medizin.client.managed.ui.AnswerToAssQuestionProxyRenderer.instance().getPaths()).fire(new Receiver<List<AnswerToAssQuestionProxy>>() {

            public void onSuccess(List<AnswerToAssQuestionProxy> response) {
                List<AnswerToAssQuestionProxy> values = new ArrayList<AnswerToAssQuestionProxy>();
                values.add(null);
                values.addAll(response);
                view.setAnswersToAssQuestionPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends medizin.client.scaffold.place.ProxyEditView<medizin.client.managed.request.AssesmentQuestionProxy, V>> extends ProxyEditView<AssesmentQuestionProxy, V> {

        void setRewiewerPickerValues(Collection<PersonProxy> values);

        void setAutorPickerValues(Collection<PersonProxy> values);

        void setQuestionPickerValues(Collection<QuestionProxy> values);

        void setAssesmentPickerValues(Collection<AssesmentProxy> values);

        void setAnswersToAssQuestionPickerValues(Collection<AnswerToAssQuestionProxy> values);
    }
}
