// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.RequestContext;
import medizin.client.managed.request.ApplicationRequestFactory;
import medizin.client.managed.request.InstitutionProxy;
import medizin.client.managed.request.InstitutionRequest;
import medizin.client.managed.ui.InstitutionDetailsView;
import medizin.client.managed.ui.InstitutionEditView;
import medizin.client.managed.ui.InstitutionListView;
import medizin.client.managed.ui.InstitutionMobileDetailsView;
import medizin.client.managed.ui.InstitutionMobileEditView;
import medizin.client.scaffold.ScaffoldApp;
import medizin.client.scaffold.place.CreateAndEditProxy;
import medizin.client.scaffold.place.FindAndEditProxy;
import medizin.client.scaffold.place.ProxyPlace;

public class InstitutionActivitiesMapper {

    private final ApplicationRequestFactory requests;

    private final PlaceController placeController;

    public InstitutionActivitiesMapper(ApplicationRequestFactory requests, PlaceController placeController) {
        this.requests = requests;
        this.placeController = placeController;
    }

    public Activity getActivity(ProxyPlace place) {
        switch(place.getOperation()) {
            case DETAILS:
                return new InstitutionDetailsActivity((EntityProxyId<InstitutionProxy>) place.getProxyId(), requests, placeController, ScaffoldApp.isMobile() ? InstitutionMobileDetailsView.instance() : InstitutionDetailsView.instance());
            case EDIT:
                return makeEditActivity(place);
            case CREATE:
                return makeCreateActivity();
        }
        throw new IllegalArgumentException("Unknown operation " + place.getOperation());
    }

    @SuppressWarnings("unchecked")
    private EntityProxyId<medizin.client.managed.request.InstitutionProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<InstitutionProxy>) place.getProxyId();
    }

    private Activity makeCreateActivity() {
        InstitutionEditView.instance().setCreating(true);
        final InstitutionRequest request = requests.institutionRequest();
        Activity activity = new CreateAndEditProxy<InstitutionProxy>(InstitutionProxy.class, request, ScaffoldApp.isMobile() ? InstitutionMobileEditView.instance() : InstitutionEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(InstitutionProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new InstitutionEditActivityWrapper(requests, ScaffoldApp.isMobile() ? InstitutionMobileEditView.instance() : InstitutionEditView.instance(), activity, null);
    }

    private Activity makeEditActivity(ProxyPlace place) {
        InstitutionEditView.instance().setCreating(false);
        EntityProxyId<InstitutionProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<InstitutionProxy>(proxyId, requests, ScaffoldApp.isMobile() ? InstitutionMobileEditView.instance() : InstitutionEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(InstitutionProxy proxy) {
                InstitutionRequest request = requests.institutionRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new InstitutionEditActivityWrapper(requests, ScaffoldApp.isMobile() ? InstitutionMobileEditView.instance() : InstitutionEditView.instance(), activity, proxyId);
    }
}
