// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.RequestContext;
import medizin.client.managed.request.ApplicationRequestFactory;
import medizin.client.managed.request.PersonProxy;
import medizin.client.managed.request.QuestionAccessProxy;
import medizin.client.managed.request.QuestionAccessRequest;
import medizin.client.managed.request.QuestionEventProxy;
import medizin.client.managed.request.QuestionProxy;
import medizin.client.managed.ui.QuestionAccessDetailsView;
import medizin.client.managed.ui.QuestionAccessEditView;
import medizin.client.managed.ui.QuestionAccessListView;
import medizin.client.managed.ui.QuestionAccessMobileDetailsView;
import medizin.client.managed.ui.QuestionAccessMobileEditView;
import medizin.client.scaffold.ScaffoldApp;
import medizin.client.scaffold.place.CreateAndEditProxy;
import medizin.client.scaffold.place.FindAndEditProxy;
import medizin.client.scaffold.place.ProxyPlace;
import medizin.client.shared.AccessRights;

public class QuestionAccessActivitiesMapper {

    private final ApplicationRequestFactory requests;

    private final PlaceController placeController;

    public QuestionAccessActivitiesMapper(ApplicationRequestFactory requests, PlaceController placeController) {
        this.requests = requests;
        this.placeController = placeController;
    }

    public Activity getActivity(ProxyPlace place) {
        switch(place.getOperation()) {
            case DETAILS:
                return new QuestionAccessDetailsActivity((EntityProxyId<QuestionAccessProxy>) place.getProxyId(), requests, placeController, ScaffoldApp.isMobile() ? QuestionAccessMobileDetailsView.instance() : QuestionAccessDetailsView.instance());
            case EDIT:
                return makeEditActivity(place);
            case CREATE:
                return makeCreateActivity();
        }
        throw new IllegalArgumentException("Unknown operation " + place.getOperation());
    }

    @SuppressWarnings("unchecked")
    private EntityProxyId<medizin.client.managed.request.QuestionAccessProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<QuestionAccessProxy>) place.getProxyId();
    }

    private Activity makeCreateActivity() {
        QuestionAccessEditView.instance().setCreating(true);
        final QuestionAccessRequest request = requests.questionAccessRequest();
        Activity activity = new CreateAndEditProxy<QuestionAccessProxy>(QuestionAccessProxy.class, request, ScaffoldApp.isMobile() ? QuestionAccessMobileEditView.instance() : QuestionAccessEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(QuestionAccessProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new QuestionAccessEditActivityWrapper(requests, ScaffoldApp.isMobile() ? QuestionAccessMobileEditView.instance() : QuestionAccessEditView.instance(), activity, null);
    }

    private Activity makeEditActivity(ProxyPlace place) {
        QuestionAccessEditView.instance().setCreating(false);
        EntityProxyId<QuestionAccessProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<QuestionAccessProxy>(proxyId, requests, ScaffoldApp.isMobile() ? QuestionAccessMobileEditView.instance() : QuestionAccessEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(QuestionAccessProxy proxy) {
                QuestionAccessRequest request = requests.questionAccessRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new QuestionAccessEditActivityWrapper(requests, ScaffoldApp.isMobile() ? QuestionAccessMobileEditView.instance() : QuestionAccessEditView.instance(), activity, proxyId);
    }
}
