// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import medizin.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    StaticToAssesmentRequest staticToAssesmentRequest();

    StaticContentRequest staticContentRequest();

    QuestionTypeRequest questionTypeRequest();

    QuestionTypeCountPerExamRequest questionTypeCountPerExamRequest();

    QuestionSumPerPersonRequest questionSumPerPersonRequest();

    QuestionRequest questionRequest();

    QuestionEventRequest questionEventRequest();

    QuestionAccessRequest questionAccessRequest();

    PersonRequest personRequest();

    McRequest mcRequest();

    KeywordRequest keywordRequest();

    InstitutionRequest institutionRequest();

    EventAccessRequest eventAccessRequest();

    CommentRequest commentRequest();

    AssesmentQuestionRequest assesmentQuestionRequest();

    AssesmentRequest assesmentRequest();

    AnswerToAssQuestionRequest answerToAssQuestionRequest();

    AnswerRequest answerRequest();
}
