// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.Date;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.Assesment")
@ProxyForName("medizin.server.domain.Assesment")
public interface AssesmentProxy extends EntityProxy {

    abstract String getName();

    abstract void setName(String name);

    abstract Date getDateOfAssesment();

    abstract void setDateOfAssesment(Date dateOfAssesment);

    abstract Date getDateOpen();

    abstract void setDateOpen(Date dateOpen);

    abstract Date getDateClosed();

    abstract void setDateClosed(Date dateClosed);

    abstract String getPlace();

    abstract void setPlace(String place);

    abstract String getLogo();

    abstract void setLogo(String logo);

    abstract Boolean getIsClosed();

    abstract void setIsClosed(Boolean isClosed);

    abstract Integer getAssesmentVersion();

    abstract void setAssesmentVersion(Integer assesmentVersion);

    abstract McProxy getMc();

    abstract void setMc(McProxy mc);

    abstract medizin.client.managed.request.AssesmentProxy getRepeFor();

    abstract void setRepeFor(medizin.client.managed.request.AssesmentProxy repeFor);

    abstract Integer getPercentSameQuestion();

    abstract void setPercentSameQuestion(Integer percentSameQuestion);

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);
}
