// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.EventAccess")
@ServiceName("medizin.server.domain.EventAccess")
public interface EventAccessRequest extends RequestContext {

    abstract Request<java.lang.Long> countEventAccesses();

    abstract Request<java.util.List<medizin.client.managed.request.EventAccessProxy>> findAllEventAccesses();

    abstract Request<java.util.List<medizin.client.managed.request.EventAccessProxy>> findEventAccessEntries(int firstResult, int maxResults);

    abstract Request<medizin.client.managed.request.EventAccessProxy> findEventAccess(Long id);

    abstract InstanceRequest<medizin.client.managed.request.EventAccessProxy, java.lang.Void> remove();

    abstract InstanceRequest<medizin.client.managed.request.EventAccessProxy, java.lang.Void> persist();
}
