// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.Date;
import java.util.Set;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.Question")
@ProxyForName("medizin.server.domain.Question")
public interface QuestionProxy extends EntityProxy {

    abstract String getQuestionText();

    abstract void setQuestionText(String questionText);

    abstract String getPicturePath();

    abstract void setPicturePath(String picturePath);

    abstract Double getQuestionVersion();

    abstract void setQuestionVersion(Double questionVersion);

    abstract Boolean getIsAcceptedRewiever();

    abstract void setIsAcceptedRewiever(Boolean isAcceptedRewiever);

    abstract Boolean getIsAcceptedAdmin();

    abstract void setIsAcceptedAdmin(Boolean isAcceptedAdmin);

    abstract Boolean getIsActive();

    abstract void setIsActive(Boolean isActive);

    abstract medizin.client.managed.request.QuestionProxy getPreviousVersion();

    abstract void setPreviousVersion(medizin.client.managed.request.QuestionProxy previousVersion);

    abstract Set<medizin.client.managed.request.KeywordProxy> getKeywords();

    abstract void setKeywords(Set<KeywordProxy> keywords);

    abstract QuestionEventProxy getQuestEvent();

    abstract void setQuestEvent(QuestionEventProxy questEvent);

    abstract CommentProxy getComment();

    abstract void setComment(CommentProxy comment);

    abstract QuestionTypeProxy getQuestionType();

    abstract void setQuestionType(QuestionTypeProxy questionType);

    abstract Set<medizin.client.managed.request.McProxy> getMcs();

    abstract void setMcs(Set<McProxy> mcs);

    abstract Set<medizin.client.managed.request.AnswerProxy> getAnswers();

    abstract void setAnswers(Set<AnswerProxy> answers);

    abstract Date getDateAdded();

    abstract void setDateAdded(Date dateAdded);

    abstract Date getDateChanged();

    abstract void setDateChanged(Date dateChanged);

    abstract PersonProxy getRewiewer();

    abstract void setRewiewer(PersonProxy rewiewer);

    abstract PersonProxy getAutor();

    abstract void setAutor(PersonProxy autor);

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);
}
