// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.QuestionTypeCountPerExam")
@ServiceName("medizin.server.domain.QuestionTypeCountPerExam")
public interface QuestionTypeCountPerExamRequest extends RequestContext {

    abstract InstanceRequest<medizin.client.managed.request.QuestionTypeCountPerExamProxy, java.lang.Void> persist();

    abstract InstanceRequest<medizin.client.managed.request.QuestionTypeCountPerExamProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countQuestionTypeCountPerExams();

    abstract Request<java.util.List<medizin.client.managed.request.QuestionTypeCountPerExamProxy>> findAllQuestionTypeCountPerExams();

    abstract Request<medizin.client.managed.request.QuestionTypeCountPerExamProxy> findQuestionTypeCountPerExam(Long id);

    abstract Request<java.util.List<medizin.client.managed.request.QuestionTypeCountPerExamProxy>> findQuestionTypeCountPerExamEntries(int firstResult, int maxResults);
}
