// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.QuestionType")
@ServiceName("medizin.server.domain.QuestionType")
public interface QuestionTypeRequest extends RequestContext {

    abstract InstanceRequest<medizin.client.managed.request.QuestionTypeProxy, java.lang.Void> persist();

    abstract InstanceRequest<medizin.client.managed.request.QuestionTypeProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countQuestionTypes();

    abstract Request<java.util.List<medizin.client.managed.request.QuestionTypeProxy>> findAllQuestionTypes();

    abstract Request<medizin.client.managed.request.QuestionTypeProxy> findQuestionType(Long id);

    abstract Request<java.util.List<medizin.client.managed.request.QuestionTypeProxy>> findQuestionTypeEntries(int firstResult, int maxResults);
}
