// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.Question")
@ServiceName("medizin.server.domain.Question")
public interface QuestionRequest extends RequestContext {

    abstract Request<java.lang.Long> countQuestions();

    abstract Request<java.util.List<medizin.client.managed.request.QuestionProxy>> findAllQuestions();

    abstract Request<medizin.client.managed.request.QuestionProxy> findQuestion(Long id);

    abstract Request<java.util.List<medizin.client.managed.request.QuestionProxy>> findQuestionEntries(int firstResult, int maxResults);

    abstract InstanceRequest<medizin.client.managed.request.QuestionProxy, java.lang.Void> persist();

    abstract InstanceRequest<medizin.client.managed.request.QuestionProxy, java.lang.Void> remove();

    abstract InstanceRequest<medizin.client.managed.request.QuestionProxy, java.lang.Void> countRedactionalBases();

    abstract InstanceRequest<medizin.client.managed.request.QuestionProxy, java.lang.Void> findAllRedactionalBases();

    abstract InstanceRequest<medizin.client.managed.request.QuestionProxy, java.lang.Void> findRedactionalBase(Long id);

    abstract InstanceRequest<medizin.client.managed.request.QuestionProxy, java.lang.Void> findRedactionalBaseEntries(int firstResult, int maxResults);
}
