// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.QuestionAccess")
@ServiceName("medizin.server.domain.QuestionAccess")
public interface QuestionAccessRequest extends RequestContext {

    abstract InstanceRequest<medizin.client.managed.request.QuestionAccessProxy, java.lang.Void> persist();

    abstract InstanceRequest<medizin.client.managed.request.QuestionAccessProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countQuestionAccesses();

    abstract Request<java.util.List<medizin.client.managed.request.QuestionAccessProxy>> findAllQuestionAccesses();

    abstract Request<medizin.client.managed.request.QuestionAccessProxy> findQuestionAccess(Long id);

    abstract Request<java.util.List<medizin.client.managed.request.QuestionAccessProxy>> findQuestionAccessEntries(int firstResult, int maxResults);
}
