// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("medizin.server.domain.QuestionEvent")
@ServiceName("medizin.server.domain.QuestionEvent")
public interface QuestionEventRequest extends RequestContext {

    abstract InstanceRequest<medizin.client.managed.request.QuestionEventProxy, java.lang.Void> persist();

    abstract InstanceRequest<medizin.client.managed.request.QuestionEventProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countQuestionEvents();

    abstract Request<java.util.List<medizin.client.managed.request.QuestionEventProxy>> findAllQuestionEvents();

    abstract Request<medizin.client.managed.request.QuestionEventProxy> findQuestionEvent(Long id);

    abstract Request<java.util.List<medizin.client.managed.request.QuestionEventProxy>> findQuestionEventEntries(int firstResult, int maxResults);
}
