package medizin.client.a_nonroo.app.request;
import medizin.client.managed.request.ApplicationRequestFactory;
import medizin.client.managed.request.StaticToAssesmentRequest;

import com.google.gwt.requestfactory.shared.RequestFactory;

/**
 * "API generated" factory interface to build request objects for the methods of
 * {@link com.google.gwt.sample.expenses.server.domain}. Client code can
 * GWT.create() an instance of this interface to build and fire request objects.
 * <p>
 * IRL this interface will be generated by a JPA-savy tool run before
 * compilation.
 */

public interface McAppRequestFactory extends ApplicationRequestFactory {

	

	



}
